export const industries = [
  "Technology",
  "Software Development",
  "Information Technology",
  "Financial Services",
  "Healthcare",
  "Education",
  "Retail",
  "E-Commerce",
  "Manufacturing",
  "Marketing",
  "Construction",
  "Consulting",
  "Legal",
  "Real Estate",
  "Government",
  "Non-Profit",
  "Other",
];
